### PR TITLE
#424 distribute replica forests evenly

### PR DESCRIPTION
**Pull request by dmcassel**
I kept the original code as the GroupedReplicaBuilderStrategy, but set up DistributedReplicaBuilderStrategy to spread replicas out better.

### CODE REVIEW

**Comment by rjrudin** [comment]
I like this direction - I will try to look at this later today or on Monday.

**Comment by dmcassel** [comment]
@rjrudin any chance this can be part of v3.12.0?

**Comment by rjrudin** [comment]
Yes, and I'll get to it today, carving out tools time today.

**Comment by rjrudin** [comment]
@dmcassel I am thinking that GroupedReplicaBuilderStrategy should be deprecated as a result of this. I was thinking it should just be deleted, but deprecating seems safer for now. Agree? If so, I'm going to add a test for it just to show the difference between it and the preferred Distributed strategy.

Going to make one other small tweak - I'm going to turn ReplicaBuilderStrategy into an interface and then create AbstractReplicaBuilderStrategy to have common code. I'll do this in a separate commit and then merge both commits into dev. 

Thanks for putting this together!

**Pull request merged**
