### PR TITLE
#244 Construction of a RestTemplate can now be customized

### PR DESCRIPTION
**Pull request by rjrudin**

### CODE REVIEW

**Comment by rjrudin** [comment]
@derms This is what I had in mind for allowing easy customization of how a RestTemplate is constructed. I added your recommendation too for calling "useSystemProperties".

**Comment by derms** [comment]
looks good @rjrudin - like the approach

Stylistically, for RestTemplateUtil, I would have gone with adding overloaded methods wherein people could specify their own configurers to use while still retaining the current behaviour for the existing methods.

Also, I think it would be a good idea to make the default static configurers as a private List (personally I'm not a fan of public field access for mutable objects) and initialise it via a private static method (so that you can handle exceptions better if the occur)


example below -

```
public class RestTemplateUtil {

	private final static Logger logger = LoggerFactory.getLogger(RestTemplateUtil.class);

    private static final List<HttpClientBuilderConfigurer> DEFAULT_CONFIGURERS = initDefaultConfigurers();
    
	public static RestTemplate newRestTemplate(String host, int port, String username, String password) {
		return newRestTemplate(new RestConfig(host, port, username, password),DEFAULT_CONFIGURERS);
	}

    public static RestTemplate newRestTemplate(String host, int port, String username, String password, HttpClientBuilderConfigurer...configurers) {
		return newRestTemplate(new RestConfig(host, port, username, password),configurers);
    }
    
    public static RestTemplate newRestTemplate(RestConfig config) {
        return newRestTemplate(new RestConfig(host, port, username, password),DEFAULT_CONFIGURERS);
    }

	public static RestTemplate newRestTemplate(RestConfig config,HttpClientBuilderConfigurer...configurers) {
		HttpClientBuilder httpClientBuilder = HttpClientBuilder.create();

		if (configurers != null) {
			for (HttpClientBuilderConfigurer configurer : configurers) {
				httpClientBuilder = configurer.configureHttpClientBuilder(config, httpClientBuilder);
			}
		}

		HttpClient client = httpClientBuilder.build();
		RestTemplate rt = new RestTemplate(new HttpComponentsClientHttpRequestFactory(client));
		rt.setErrorHandler(new MgmtResponseErrorHandler());
		return rt;
	}

    private static final List<HttpClientBuilderConfigurer> initDefaultConfigurers() {
        List<HttpClientBuilderConfigurer>  configurers =new ArrayList<>();
        configurers.add(new BasicAuthConfigurer());
		configurers.add(new SslConfigurer());
		configurers.add(new NoConnectionReuseConfigurer());
        configurers.add(new UseSystemPropertiesConfigurer());
        return Collections.unmodifiableList(configurers);
    }
    
}
```

**Comment by rjrudin** [comment]
Thanks @derms  - I added the overloaded methods so that configurers can be passed in.

My reasoning for the public/static List is so that e.g. an ml-gradle client can manipulate the List from within build.gradle. I agree about not liking such things typically, but this provides an escape hatch for complete customization of how the HttpClient is constructed.

**Comment by derms** [comment]
Thanks @rjrudin  - makes sense regards the public/static List and understand the reasoning behind it now 👍

**Pull request merged**
